### ISSUE TITLE
Bug while getting advertising data

### ISSUE THREAD

**Issue by andreh1111** [ThomasGerstenberg/blatann#104]
Hi,
I think I found a bug while getting advertising data.
This is the error I get:

> Traceback (most recent call last):
>    File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\blatann\nrf\nrf_driver.py", line 701, in _event_handler
>      handler(self, event)
>    File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\blatann\gap\scanning.py", line 135, in _on_adv_report
>      scan_report = self.scan_report.update(adv_report)
>    File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\blatann\gap\advertise_data.py", line 376, in update
>      scan_entry = ScanReport(adv_report)
>    File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\blatann\gap\advertise_data.py", line 286, in __init__
>      self.advertise_data = AdvertisingData.from_ble_adv_records(self._current_advertise_data)
>    File "C:\Users\andre\AppData\Local\Programs\Python\Python38\lib\site-packages\blatann\gap\advertise_data.py", line 219, in from_ble_adv_records
>      uuid16 = (uuid16_data[i+1] << 8) | uuid16_data[i]
>  IndexError: list index out of range

This is a minimal code I used to get this error:

```
from blatann import BleDevice
ble_device = BleDevice('COMx')
ble_device.open()
reports = ble_device.scanner.start_scan().scan_reports
for report in reports:
    print(report)
ble_device.close()
```

In particular, when the error occurs, the variable _uuid16_data_ in _\gap\advertise_data.py_ is equal to [18, 162, 77, 46, 254, 20, 72, 142, 147, 210, 23, 60, 253, 2, 22, 120, 9, 156, 227, 157, 0, 136, 11, 18, 64, 0, 0, 0, 0], so it has an odd length equal to 29. Hence, an IndexError is raised by the following line:
```
for i in range(0, len(uuid16_data), 2):
    uuid16 = (uuid16_data[i+1] << 8) | uuid16_data[I]
```

I will be available for further clarifications, thank you for your amazing work

**Comment by ThomasGerstenberg** [comment]
Thank you for reporting! I'll look into this. Ultimately there shouldn't be an odd number of bytes, but regardless the library should be able to gracefully handle this case. I'll get a fix in for the next release
