### ISSUE TITLE
scanner.py doesn't work on Windows 10

### ISSUE THREAD

**Issue by snowuyl** [ThomasGerstenberg/blatann#119]
nRF Connect can scan BLE device. But the following doesn't have any response.
D:\Python\Python37\python.exe .\scanner.py

**Comment by snowuyl** [comment]
<img width="960" alt="ANCS1" src="https://user-images.githubusercontent.com/8336439/177699392-146f8b65-563a-472e-b4c7-6a55f9ac5ede.png">
[scanner.zip](https://github.com/ThomasGerstenberg/blatann/files/9060686/scanner.zip)

**Comment by snowuyl** [comment]
<img width="960" alt="nRF_Connect_USB_CDC_ACM" src="https://user-images.githubusercontent.com/8336439/177699674-92f34701-27da-402f-8f4b-2780796f1cd1.png">

**Comment by ThomasGerstenberg** [comment]
The command line needs a second parameter with the name of the port, e.g. `D:\Python\Python37\python.exe .\scanner.py COM5`. This has been tested on windows extensively and should work as expected
