### ISSUE TITLE
ram overflow problem since too many characteristic added to the service 

### ISSUE THREAD

**Issue by juntujerry** [ThomasGerstenberg/blatann#125]
if we continue to use add_service and add_characteristic_to_service, the ram eventually will be overflow.
Is there a way to remove exist characteristic or service, or a purely reset function to do that?how to remove characteristic and service in current adaptor? 

eg: remove_characteristic_to_service()

Thanks

**Comment by ThomasGerstenberg** [comment]
Unfortunately that's a limitation of the Nordic firmware, and not a normal use-case for BLE. Typically characteristics aren't removed from your local GATT database, and only need to be added once when setting up the device. 

If you're trying to use different GATT databases, you can close and re-open the device which will reset the firmware and clear everything out
