### ISSUE TITLE
multi threading unsafety.

### ISSUE THREAD

**Issue by juntujerry** [ThomasGerstenberg/blatann#126]
Eg: below code will have error 

I believe your ble_device.close() function is running inside kernel as a thread.

right after calling ble_device.close(), if you make a call to ble_device.open(), it will failed.
unless, I put some delay between close and open. 

<code>
#python start
import time
import threading
from blatann import BleDevice
from blatann.gap.advertising import AdvertisingMode, AdvertisingData, AdvertisingFlags
from blatann.examples import example_utils

logger = example_utils.setup_logger(level="DEBUG")

def _get_time_service_data():
    # Get the current time
    t = time.strftime("%H:%M:%S", time.localtime())
    # Service data is 2 bytes UUID + data, use UUID 0x2143
    return "\x43\x21" + t

def main(serial_port):
    ble_device = BleDevice(serial_port)
    ble_device.open()

    interval_ms = 100  # Send out an advertising packet every 100ms
    timeout_sec = 0    # Advertise forever
    mode = AdvertisingMode.non_connectable_undirected  # Set mode to not allow connections

    adv_flags = AdvertisingFlags.BR_EDR_NOT_SUPPORTED | AdvertisingFlags.GENERAL_DISCOVERY_MODE
    adv_data = AdvertisingData(flags=adv_flags, local_name="Time", service_data=_get_time_service_data())

    ble_device.advertiser.set_advertise_data(adv_data)
    ble_device.advertiser.start(interval_ms, timeout_sec, auto_restart=True, advertise_mode=mode)

    count = 0

    while True:
        # Update the service data and set it in the BLE device
        adv_data.service_data = _get_time_service_data()
        ble_device.advertiser.set_advertise_data(adv_data)
        count = count + 1
        if ( count > 4 ):
            break

    ble_device.advertiser.stop()
    ble_device.close()

if __name__ == '__main__':
    main("/dev/ttyACM0")
    #time.sleep(4)
    main("/dev/ttyACM0")
#python end
</code>

**Comment by ThomasGerstenberg** [comment]
This is a known issue (#75). This is an issue using USB-CDC interface rather than serial since when the device is closed, the micro is reset which also hosts the USB-CDC device. So the OS needs to re-enumerate the USB port when the micro comes back up after reset
