### ISSUE TITLE
static private ble address and static private non-resolvable address is not supported. 

### ISSUE THREAD

**Issue by juntujerry** [ThomasGerstenberg/blatann#127]
So only public and static random address are supppoorted.

If I set ble address to be Non-Resolvable Random Private Address, It won't work, My Mac address address bit is filtered properly.

I trace down the function, sd_ble_gap_addre_set function. According to S140 nortic, it only support  RANDOM STATIC  MAC address and public address, as is shown below.

![image](https://user-images.githubusercontent.com/98043825/212994069-a2d58a7a-07b4-48dc-849d-ed6b009c7da8.png)

TODO: I would like you to add a protection in middle layer, state that it is not supported. Thanks.

**Comment by ThomasGerstenberg** [comment]
Looks like private resolvable/non-resolvable addresses can be configured using [sd_ble_gap_privacy_set()](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.s140.api.v5.0.0/group___b_l_e___g_a_p___f_u_n_c_t_i_o_n_s.html#ga2203b7709d7178bc35e7f903bd0e913f). 

This currently isn't exposed in blatann, but should be pretty easy to add in
