### ISSUE TITLE
Is it possible to suppress saving bond database?

### ISSUE THREAD

**Issue by mdxs** [ThomasGerstenberg/blatann#142]
I'm looking into using Blatann with an nRF52840 dongle to interact with BLE devices in a testing environment in which the bond database isn't expected to add any value. Is it possible to suppress saving the bond database?

Currently, as I understand it and see from the logs, there is always an attempt to save the bond database. It probably also attempts to load the bond database as well. In my case the saved file is a JSON dict with an empty "records" list, and I expect this to remain empty in my usage scenario of Blatann.

I'm thinking that a special DatabaseStrategy might work (one that simply doesn't try to do any file stuff), but I guess there should also be some changes to the initialization phase to specify the use of such a "NoneDatabaseStrategy/MemoryDatabaseStrategy".

**Comment by mdxs** [comment]
Perhaps using the special filename ":memory:" to create an in-memory database (similar to SQLite).

**Comment by ThomasGerstenberg** [comment]
I like it, should be pretty straight-forward to add in a new strategy for that. The `:memory:` designator is a good suggestion.

I may have time in the next week or so to add this in. In the meantime you can work around this by overriding the current DB loader in the device to one that does nothing on load/save

```py
from blatann.gap.bond_db import BondDatabaseLoader
from blatann.gap.default_bond_db import DefaultBondDatabase

class NoopBondDbLoader(BondDatabaseLoader):
    def load(self):
        return DefaultBondDatabase()
    def save(self, db):
        # do nothing
        pass

device = BleDevice()
device.bond_db_loader = NoopBondDbLoader()
device.configure()
device.open()
```

**Comment by mdxs** [comment]
Thanks for the workaround, it works for my use case.

Looking forward to some `:memory:` database implementation.

**Comment by mdxs** [comment]
Great to see that this has been implemented.
