### ISSUE TITLE
Update short project description on GitHub

### ISSUE THREAD

**Issue by mdxs** [ThomasGerstenberg/blatann#169]
Further to a suggestion shared in a comment to #161 (and #167 for PR to change `setup.py`), this ticket proposed for @ThomasGerstenberg to change the short project description on GitHub to "Python BLE library for using Nordic nRF52 with Connectivity firmware". The screenshots below provide hints on the procedure to follow,

![blatann-edit-gh-prj-settings](https://github.com/ThomasGerstenberg/blatann/assets/1143642/8204740b-c1bb-44ff-9d04-1c30999afef9)

![blatann-edit-gh-prj-dialog](https://github.com/ThomasGerstenberg/blatann/assets/1143642/9424dcdc-0720-4f66-9467-25bf8c5e4007)

**Comment by ThomasGerstenberg** [comment]
Done
