### ISSUE TITLE
Cryptography Deprecation Warning

### ISSUE THREAD

**Issue by regin-mBohm** [ThomasGerstenberg/blatann#185]
I get 
Python\Python310\lib\site-packages\blatann\gap\smp_crypto.py:81: CryptographyDeprecationWarning: Curve argument must be an instance of an EllipticCurve class. Did you pass a class by mistake? This will be an exception in a future version of cryptography.
  return ec.generate_private_key(_lesc_curve, _backend)

when I do BleDevice.open()

Have not had this issue before so somethings changed in cryptography perhaps?

**Comment by ThomasGerstenberg** [comment]
Yes, the cryptography library recently marked something as deprecated so it's starting to show up. It's been fixed already (#180), I'll make a new release with that change to remove the warning
