### ISSUE TITLE
Event length parameter

### ISSUE THREAD

**Issue by jaclim** [ThomasGerstenberg/blatann#78]
Hello, I have a question regarding the (gap) event length value blatann is using.
Is the value fixed at 7.5ms as mentioned in the changelog for version v0.3.1?
![event_length](https://user-images.githubusercontent.com/74769997/118669608-2f663f80-b7f6-11eb-8158-fe0713aa79fe.PNG)

Best regards,
jaclim

**Comment by ThomasGerstenberg** [comment]
Yes, currently it's set to 6 events (1.25ms per event) without a formal API to change it. However you can change it by updating [this private property](https://github.com/ThomasGerstenberg/blatann/blob/86366bc38d84f3ddb22314aa1ca50ee28be8b916/blatann/device.py#L120) before opening: `ble_device._default_conn_config.event_length = x`, where x is the number of 1.25ms events (default 6). 
Alternatively if anyone feels strong enough it can be added to the `BleDevice.configure()` parameter list for a proper API
