### ISSUE TITLE
How to get the RSSI of an active connection

### ISSUE THREAD

**Issue by rds-tmeyer** [ThomasGerstenberg/blatann#97]
Hi,

First, thanks a lot for this amazing library. It's the most feature complete cross-platform implementation of a python BLE library I've come across. 

I'm trying to get the RSSI of an active connection with a peripheral (Blatann is used as central). I can get it while scanning the device, before connection, but I'm unable to find the API to request the updated RSSI once connected. Is there any ?

Thanks,
Théo

**Comment by ThomasGerstenberg** [comment]
Thank you for the kind words!

Reading RSSI of an active connection isn't yet supported, but doesn't look too bad to add in.
Unfortunately I've been extremely busy and I haven't had much time to work on this library (as evidenced by the other recent feature requests I've neglected). I can't commit to when I could get around to it, but hopefully soon-ish
